name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-package:
    name: Build & Package on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Setup Gradle 8.14.2
        uses: gradle/actions/setup-gradle@v4.0.0
        with:
          gradle-version: '8.14.2'

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Package with jpackage
        run: ./gradlew jpackage

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: packaged-app-${{ matrix.os }}
          path: build/jpackage/**

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Setup Gradle 8.14.2
        uses: gradle/actions/setup-gradle@v4.0.0
        with:
          gradle-version: '8.14.2'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4.0.0

  release:
    needs: build-and-package
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Download all packages
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            自动化打包并发布，包含Linux、Windows、macOS版本。
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}